version: '3.8'

services:
  uxnote-app:
    build: .
    container_name: uxnote-app
    restart: unless-stopped
    volumes:
      - uxnote_data:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "docker-volume-backup.stop-during-backup=true"

  uxnote-backup:
    image: offen/docker-volume-backup:latest
    restart: always
    environment:
      AWS_S3_BUCKET_NAME: ${BACKUP_S3_BUCKET:-familiar-couper}
      AWS_ENDPOINT: ${BACKUP_S3_ENDPOINT:-https://s3.gra.io.cloud.ovh.net/}
      AWS_ACCESS_KEY_ID: ${BACKUP_S3_KEY}
      AWS_SECRET_ACCESS_KEY: ${BACKUP_S3_SECRET}
      AWS_REGION: gra
      AWS_S3_PATH: uxnote-backups
      BACKUP_CRON_EXPRESSION: "0 * * * *"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_FILENAME: "uxnote-backup-%Y-%m-%dT%H-%M-%S.tar.gz"
    volumes:
      - uxnote_data:/backup/uxnote_data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  uxnote_data:
    driver: local
